// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: customer_addresses_queries.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCustomerAddress = `-- name: CreateCustomerAddress :one
INSERT INTO customer_addresses (street_address, state, zip_code, country, customer_id, last_modified_at, last_modified_by)
    VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING
    id, street_address, state, zip_code, country, customer_id, last_modified_at, last_modified_by
`

type CreateCustomerAddressParams struct {
	StreetAddress  string
	State          pgtype.Text
	ZipCode        pgtype.Text
	Country        pgtype.Text
	CustomerID     string
	LastModifiedAt pgtype.Timestamptz
	LastModifiedBy string
}

func (q *Queries) CreateCustomerAddress(ctx context.Context, arg CreateCustomerAddressParams) (CustomerAddress, error) {
	row := q.db.QueryRow(ctx, createCustomerAddress,
		arg.StreetAddress,
		arg.State,
		arg.ZipCode,
		arg.Country,
		arg.CustomerID,
		arg.LastModifiedAt,
		arg.LastModifiedBy,
	)
	var i CustomerAddress
	err := row.Scan(
		&i.ID,
		&i.StreetAddress,
		&i.State,
		&i.ZipCode,
		&i.Country,
		&i.CustomerID,
		&i.LastModifiedAt,
		&i.LastModifiedBy,
	)
	return i, err
}

const deleteCustomerAddress = `-- name: DeleteCustomerAddress :exec
DELETE FROM customer_addresses
WHERE customer_id = $1
    AND id = $2
`

type DeleteCustomerAddressParams struct {
	CustomerID string
	ID         string
}

func (q *Queries) DeleteCustomerAddress(ctx context.Context, arg DeleteCustomerAddressParams) error {
	_, err := q.db.Exec(ctx, deleteCustomerAddress, arg.CustomerID, arg.ID)
	return err
}

const getCustomerAddress = `-- name: GetCustomerAddress :one
SELECT
    id,
    street_address,
    state,
    zip_code,
    country,
    customer_id,
    last_modified_at,
    last_modified_by
FROM
    customer_addresses
WHERE
    customer_id = $1
    AND id = $2
`

type GetCustomerAddressParams struct {
	CustomerID string
	ID         string
}

func (q *Queries) GetCustomerAddress(ctx context.Context, arg GetCustomerAddressParams) (CustomerAddress, error) {
	row := q.db.QueryRow(ctx, getCustomerAddress, arg.CustomerID, arg.ID)
	var i CustomerAddress
	err := row.Scan(
		&i.ID,
		&i.StreetAddress,
		&i.State,
		&i.ZipCode,
		&i.Country,
		&i.CustomerID,
		&i.LastModifiedAt,
		&i.LastModifiedBy,
	)
	return i, err
}

const getCustomerAddresses = `-- name: GetCustomerAddresses :many
SELECT
    id,
    street_address,
    state,
    zip_code,
    country,
    customer_id,
    last_modified_at,
    last_modified_by
FROM
    customer_addresses
WHERE
    customer_id = $1
`

func (q *Queries) GetCustomerAddresses(ctx context.Context, customerID string) ([]CustomerAddress, error) {
	rows, err := q.db.Query(ctx, getCustomerAddresses, customerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CustomerAddress
	for rows.Next() {
		var i CustomerAddress
		if err := rows.Scan(
			&i.ID,
			&i.StreetAddress,
			&i.State,
			&i.ZipCode,
			&i.Country,
			&i.CustomerID,
			&i.LastModifiedAt,
			&i.LastModifiedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCustomerAddress = `-- name: UpdateCustomerAddress :one
UPDATE
    customer_addresses
SET
    street_address = $3,
    state = $4,
    zip_code = $5,
    country = $6,
    last_modified_at = $7,
    last_modified_by = $8
WHERE
    customer_id = $1
    AND id = $2
RETURNING
    id,
    street_address,
    state,
    zip_code,
    country,
    customer_id,
    last_modified_at,
    last_modified_by
`

type UpdateCustomerAddressParams struct {
	CustomerID     string
	ID             string
	StreetAddress  string
	State          pgtype.Text
	ZipCode        pgtype.Text
	Country        pgtype.Text
	LastModifiedAt pgtype.Timestamptz
	LastModifiedBy string
}

func (q *Queries) UpdateCustomerAddress(ctx context.Context, arg UpdateCustomerAddressParams) (CustomerAddress, error) {
	row := q.db.QueryRow(ctx, updateCustomerAddress,
		arg.CustomerID,
		arg.ID,
		arg.StreetAddress,
		arg.State,
		arg.ZipCode,
		arg.Country,
		arg.LastModifiedAt,
		arg.LastModifiedBy,
	)
	var i CustomerAddress
	err := row.Scan(
		&i.ID,
		&i.StreetAddress,
		&i.State,
		&i.ZipCode,
		&i.Country,
		&i.CustomerID,
		&i.LastModifiedAt,
		&i.LastModifiedBy,
	)
	return i, err
}
