// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package postgres

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Customer struct {
	ID             string
	FirstName      string
	LastName       string
	LastModifiedAt pgtype.Timestamptz
	LastModifiedBy string
	DeletedAt      pgtype.Timestamptz
	TenantID       string
}

type CustomerAddress struct {
	ID             string
	StreetAddress  string
	State          pgtype.Text
	ZipCode        pgtype.Text
	Country        pgtype.Text
	CustomerID     string
	LastModifiedAt pgtype.Timestamptz
	LastModifiedBy string
}

type CustomerEmailAddress struct {
	ID             string
	EmailAddress   string
	Type           string
	CustomerID     string
	LastModifiedAt pgtype.Timestamptz
	LastModifiedBy string
}

type CustomerNote struct {
	ID             string
	Note           string
	CustomerID     string
	LastModifiedAt pgtype.Timestamptz
	LastModifiedBy string
}

type CustomerPhoneNumber struct {
	ID             string
	CustomerID     string
	PhoneNumber    string
	Type           string
	LastModifiedAt pgtype.Timestamptz
	LastModifiedBy string
}

type Interaction struct {
	ID              string
	QueueID         string
	State           string
	StateModifiedAt pgtype.Timestamptz
	UserID          pgtype.Text
	TenantID        string
	CreatedAt       pgtype.Timestamptz
	Type            string
}

type InteractionNote struct {
	ID             string
	Note           string
	InteractionID  string
	LastModifiedAt pgtype.Timestamptz
	LastModifiedBy string
}

type Queue struct {
	ID             string
	Name           string
	TenantID       string
	LastModifiedAt pgtype.Timestamptz
	LastModifiedBy string
	DeletedAt      pgtype.Timestamptz
}

type Skill struct {
	ID             string
	Name           string
	TenantID       string
	LastModifiedAt pgtype.Timestamptz
	LastModifiedBy string
	DeletedAt      pgtype.Timestamptz
}

type Tenant struct {
	ID             string
	Name           string
	LastModifiedAt pgtype.Timestamptz
	LastModifiedBy string
	DeletedAt      pgtype.Timestamptz
}

type User struct {
	ID             string
	FirstName      string
	LastName       string
	EmailAddress   string
	TenantID       string
	LastModifiedAt pgtype.Timestamptz
	LastModifiedBy string
	DeletedAt      pgtype.Timestamptz
}

type UserPresence struct {
	UserID         string
	Presence       string
	LastModifiedAt pgtype.Timestamptz
	LastModifiedBy string
}

type UserSkill struct {
	UserID     string
	SkillID    string
	SkillLevel int32
}
