// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package postgres

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Queue struct {
	ID             string
	Name           string
	TenantID       string
	LastModifiedAt pgtype.Timestamptz
	LastModifiedBy string
	DeletedAt      pgtype.Timestamptz
}

type Skill struct {
	ID             string
	Name           string
	TenantID       string
	LastModifiedAt pgtype.Timestamptz
	LastModifiedBy string
	DeletedAt      pgtype.Timestamptz
}

type Tenant struct {
	ID             string
	Name           string
	LastModifiedAt pgtype.Timestamptz
	LastModifiedBy string
	DeletedAt      pgtype.Timestamptz
}

type User struct {
	ID             string
	FirstName      string
	LastName       string
	EmailAddress   string
	TenantID       string
	LastModifiedAt pgtype.Timestamptz
	LastModifiedBy string
	DeletedAt      pgtype.Timestamptz
}

type UserPresence struct {
	UserID         string
	Presence       string
	LastModifiedAt pgtype.Timestamptz
	LastModifiedBy string
}

type UserSkill struct {
	UserID     string
	SkillID    string
	SkillLevel int32
}
